config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'pets', to: 'pets#index'
  # get 'pets/new', to: 'pets#new'
  # post 'pets', to: 'pets#create'
  # get 'pets/:id/edit', to: 'pets#edit'
  # patch 'pets/:id', to: 'pets#update'
  # get 'pets/:id', to: 'pets#show'
  # delete 'pets/:id', to: 'pets#destroy'

  resources :pets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = ["cat", "dog", "bird"]
  validates :species, inclusion: { in: SPECIES }
  validates :name, presence: true

  def found_days_ago
    "#{self.name} has been found #{(Date.today - self.found_on).to_i} days ago!"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pets = Pet.all
  end

  def show
  end

  def create
    @pet = Pet.new(params_pet)
    if @pet.save
      redirect_to pets_path
    else
      render :new
    end
  end

  def new
    @pet = Pet.new
  end

  def edit
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  def update
    @pet = Pet.find(params[:id])
    if @pet.update(params_pet)
      redirect_to pets_path
    else
      render :edit
    end
  end

  private

  def params_pet
    params.require(:pet).permit(:name, :address, :species, :found_on)
  end

  def set_pet
    @pet = Pet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PetLost</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
  <%= simple_form_for pet do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :species, collection: Pet::SPECIES %>
    <%= f.input :found_on %>
    <%= f.submit %>
  <% end %>

app/views/pets/edit.html.erb
<div class="container">
  <%= render "form", pet: @pet %>
</div>

app/views/pets/index.html.erb
<div class="container">
<h1 class="text-center">Pets Lost !!</h1>
<%= link_to 'Add a pet!', new_pet_path, class:"btn btn-primary" %>

  <% @pets.each do |pet| %>

    <h2> <%= link_to pet.name, pet_path(pet) %> </h2>
    <p><%= pet.address %></p>
    <p><%= pet.species %></p>
    <%= link_to "Modifier", edit_pet_path(pet), class:"btn btn-primary" %>
    <%= link_to "Supp", pet_path(pet), method: :delete, class:"btn btn-danger" %>
  <% end  %>

</div>

app/views/pets/new.html.erb
<div class="container">
  <%= render "form", pet: @pet %>
</div>

app/views/pets/show.html.erb
<h1>Pets#show</h1>

<h2><%= @pet.name %></h2>
<p><%= @pet.species %></p>

<p><%= @pet.found_days_ago %></p>
<%= link_to "< Back", pets_path, class:" btn btn-light" %>